loans:
  image:
    repository: docker.io/aperturesci/loan
    tag: v2
    pullPolicy: Always

  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

  interest:
    image:
      repository: docker.io/aperturesci/interest
      tag: v2
